### ISSUE TITLE
Separate write article screen

### ISSUE THREAD

**Issue by jonesamelia** [DiscoTrayStudios/GroundTruth#162]

**Comment by keyszl** [comment]
Hey Amelia, I think this looks good but is a little bit different than what the goal was for this issue: We wanted to have a preview screen that as you set evidence to true/false, you could see what it adds to the article. I think a different way of solving this would be to have the article preview not take up the whole part of the screen, as you have to click back then set each individual evidence to true then click back on the article preview button, etc., causing a lot of back and forth. Is it possible to make the write article page take up only half of it and evidence sticky notes to take up the other half? The split screen of these two pages should only occur when the write article button is pressed, if the user backs out it should just be the regular desk screen like it is right now.
